name: 'Execução manual'  # Nome do workflow exibido no GitHub

on:
  workflow_dispatch:     # Gatilho manual: usuário executa quando quiser

jobs:
  e2e-tests:             # Nome do job (grupo de etapas)
    runs-on: ubuntu-latest  # Máquina onde o job vai rodar

    steps:
      - uses: actions/checkout@v4  # Clona o repositório
      
      - uses: actions/setup-node@v4  # Instala o Node.js
        with:
          node-version: latest  # Usa a última versão do Node.js

      - name: 'Instalação do Yarn'
        run: npm install -g yarn     # Instala o gerenciador de pacotes Yarn
      
      - name: 'Instalação das dependências'
        run: yarn
      
      - name: 'Instalação do Playwright'
        run: yarn playwright install
      
      - name: 'Executando testes E2E com Playwright'
        run: yarn run e2e