#CI de Nivel 0102 - Disparo agendado
# Nome do workflow exibido na aba "Actions" do GitHub
name: 'Execução agendada'

# Definição do gatilho que inicia o workflow
# Neste caso, é necessário acionar manualmente (botão "Run workflow")
on:
  schedule:
    - cron: "0 10 * * *" # Executa de segunda a sexta-feira, às 7:00 AM UTC

# Definição dos jobs (tarefas que serão executadas)
jobs:
  e2e-tests:  # Nome do job. Pode conter vários "steps" (passos).
  
    # Define o sistema operacional da máquina virtual onde os passos serão executados
    runs-on: ubuntu-latest  # Usamos Ubuntu atualizado, fornecido pelo GitHub

    steps:  # Lista de etapas (steps) que serão executadas em sequência

      - uses: actions/checkout@v4  #Clone do projeto

      - uses: actions/setup-node@v4 #instalando o node na versao mais recente
        with:
          node-version: latest  

      - name: 'Instalação do Yarn' #instalaçao global yarn
        run: npm install -g yarn  

      - name: 'Instalação das dependências'
        run: yarn  
      - name: 'Instalação do Playwright'
        run: yarn playwright install  #baixa os navegadores do playwright

      #Executa os testes E2E automatizados com Playwright
      - name: 'Executando testes E2E com Playwright'
        run: yarn run e2e  